services:
  storage:
    image: redis
    volumes:
      - ./data:/data
  counter:
    image: cpbist/counter:1.0.0
    environment:
      - PORT=3001
      - REDIS_URL=redis://storage
    ports:
      - 81:3001
    depends_on:
      - storage
  liba:
    image: node:20.10
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - PORT=3002
      - COUNTER_URL=http://counter:3001/
    ports:
      - 80:3002
    command: npm run dev
    depends_on:
      - counter
